name: Sync to Synology NAS

on:
  push:
    branches:
      - main  # 'main' 브랜치에 푸시될 때마다 실행

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Deploy to Synology NAS
      run: |
        ssh -p 2222 eorkfclsrn@210.90.158.128 'cd /volume1/docker/node/lasttest && sudo git pull origin main'




