name: Sync to Synology NAS

on:
  push:
    branches:
      - main  # 'main' 브랜치에 푸시될 때마다 실행

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Sync with Synology NAS
      uses: appleboy/ssh-action@master
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 2222  # 외부에서 접속할 포트
        script: |
          cd /volume1/docker/node/lasttest
          sudo git pull origin main
