name: Sync to Synology NAS

on:
  push:
    branches:
      - main  # 'main' 브랜치에 푸시될 때마다 실행

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Sync with Synology NAS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EXTERNAL_IP }}
        username: ${{ secrets.NAS_USER }}
        key: ${{ secrets.NAS_PASSWORD }}
        port: 2222  # 외부에서 접속할 포트
        script: |
          sudo chown -R $(whoami) /volume1/docker/node/lasttest
          sudo chmod -R 755 /volume1/docker/node/lasttest
          cd /volume1/docker/node/lasttest
          sudo git pull origin main
