name: Sync to Synology NAS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set Git safe directory
      run: git config --global --add safe.directory /volume1/docker/node/lasttest
    - name: Sync with Synology NAS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EXTERNAL_IP }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 2222
        command_timeout: 30m    # ← 이 줄 추가 (기본값 10분)
        script: |
          set -e
          export PATH=$PATH:/usr/local/bin
          cd /volume1/docker/node/lasttest
          git fetch origin main
          git reset --hard origin/main
          npm install
          npm run build

          if docker ps -a --format '{{.Names}}' | grep -Fxq aura_git; then
            if docker ps --format '{{.Names}}' | grep -Fxq aura_git; then
              docker stop --time 120 aura_git
            fi

            docker start aura_git
          else
            echo "aura_git container not found"
            exit 1
          fi
